version: "3.4"

services:
  db:
    image: mysql/mysql-server
    container_name: coolestproject-db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coolestproject
      MYSQL_DATABASE: coolestproject
      MYSQL_USER: coolestproject
      MYSQL_PASSWORD: Se84KCCCJlnfkdfv

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80

  backend:
    image: coolestproject-backend
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - configuration.env
    environment:
      NODE_ENV: production
      DB: mysql://coolestproject:Se84KCCCJlnfkdfv@db:3306/coolestproject
    ports:
      - 8080:8080
    command: npm run development
    depends_on:
      - db

  frontend:
    image: coolestproject-frontend
    build: ./frontend
    environment:
      NUXT_ENV_BASE_URL: http://localhost:8080
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - configuration.env
    ports:
      - 3000:3000
    command: npm run dev2
    depends_on:
      - backend

volumes:
  db_data: {}
