version: "3.4"

services :
  proxy:    
    image: "traefik:v2.4"
    container_name: "coolestproject-proxy"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:1234"
      - "--providers.file.directory=/configuration/"
      - "--providers.file.watch=true"
    ports:
      - "1234:1234"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./configuration/:/configuration/

  db:
    image: mysql/mysql-server
    container_name: coolestproject-db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coolestproject
      MYSQL_DATABASE: coolestproject
      MYSQL_USER: coolestproject
      MYSQL_PASSWORD: Se84KCCCJlnfkdfv

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    depends_on:
      - db

  backend:
    image: coolestproject-backend
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - configuration.env
    environment:
      NODE_ENV: production
      DB: mysql://coolestproject:Se84KCCCJlnfkdfv@db:3306/coolestproject
    command: npm run development
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-coolestprojects.rule=Host(`backend.coolestprojects.localhost`)"
      - "traefik.http.routers.backend-coolestprojects.entrypoints=web"
      - "traefik.http.routers.backend-coolestprojects.tls=true"

  frontend:
    image: coolestproject-frontend
    build: ./frontend
    environment:
      NUXT_ENV_BASE_URL: https://backend.coolestprojects.localhost:1234
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - configuration.env
    command: npm run dev2
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-coolestprojects.rule=Host(`app.coolestprojects.localhost`)"
      - "traefik.http.routers.frontend-coolestprojects.entrypoints=web"
      - "traefik.http.routers.frontend-coolestprojects.tls=true"


volumes:
  db_data: {}
